package com.mvc.footprints.entity;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

// Generated 2014-11-29 12:14:13 by Hibernate Tools 3.2.2.GA

/**
 * PreUcenterMembers generated by hbm2java
 */
@Entity
@Table(name="PRE_UCENTER_MEMBERS")
public class PreUcenterMembers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6681557935694121351L;
	@Id
	private Integer uid;
	private String username;
	private String password;
	private String email = "";
	private String myid = "";
	private String myidkey = "";
	private String regip = "";
	private int regdate = 0;
	private int lastloginip = 0;
	private int lastlogintime = 0;
	private String salt = "abcdef";
	private String secques ="";
	
	private String sex;
	private String photoImgId;
	private String mobilePhone;
	private String areaId;
	private Integer age;
	private String star;
	
	@Transient
	private String phcode;
	
	@Transient
	private String areaName;

	public PreUcenterMembers() {
	}

	public PreUcenterMembers(String username, String password, String email,
			String myid, String myidkey, String regip, int regdate,
			int lastloginip, int lastlogintime, String salt, String secques) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.myid = myid;
		this.myidkey = myidkey;
		this.regip = regip;
		this.regdate = regdate;
		this.lastloginip = lastloginip;
		this.lastlogintime = lastlogintime;
		this.salt = salt;
		this.secques = secques;
	}

	public Integer getUid() {
		return this.uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMyid() {
		return this.myid;
	}

	public void setMyid(String myid) {
		this.myid = myid;
	}

	public String getMyidkey() {
		return this.myidkey;
	}

	public void setMyidkey(String myidkey) {
		this.myidkey = myidkey;
	}

	public String getRegip() {
		return this.regip;
	}

	public void setRegip(String regip) {
		this.regip = regip;
	}

	public int getRegdate() {
		return this.regdate;
	}

	public void setRegdate(int regdate) {
		this.regdate = regdate;
	}

	public int getLastloginip() {
		return this.lastloginip;
	}

	public void setLastloginip(int lastloginip) {
		this.lastloginip = lastloginip;
	}

	public int getLastlogintime() {
		return this.lastlogintime;
	}

	public void setLastlogintime(int lastlogintime) {
		this.lastlogintime = lastlogintime;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	public String getSecques() {
		return this.secques;
	}

	public void setSecques(String secques) {
		this.secques = secques;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhotoImgId() {
		return photoImgId;
	}

	public void setPhotoImgId(String photoImgId) {
		this.photoImgId = photoImgId;
	}

	public String getMobilePhone() {
		return mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	public String getAreaId() {
		return areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public Integer getAge() {
		return age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getStar() {
		return star;
	}

	public void setStar(String star) {
		this.star = star;
	}

	public String getPhcode() {
		return phcode;
	}

	public void setPhcode(String phcode) {
		this.phcode = phcode;
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PreUcenterMembers : {\n\t\"uid\" : \"");
		builder.append(uid);
		builder.append("\", \n\t\"username\" : \"");
		builder.append(username);
		builder.append("\", \n\t\"password\" : \"");
		builder.append(password);
		builder.append("\", \n\t\"email\" : \"");
		builder.append(email);
		builder.append("\", \n\t\"myid\" : \"");
		builder.append(myid);
		builder.append("\", \n\t\"myidkey\" : \"");
		builder.append(myidkey);
		builder.append("\", \n\t\"regip\" : \"");
		builder.append(regip);
		builder.append("\", \n\t\"regdate\" : \"");
		builder.append(regdate);
		builder.append("\", \n\t\"lastloginip\" : \"");
		builder.append(lastloginip);
		builder.append("\", \n\t\"lastlogintime\" : \"");
		builder.append(lastlogintime);
		builder.append("\", \n\t\"salt\" : \"");
		builder.append(salt);
		builder.append("\", \n\t\"secques\" : \"");
		builder.append(secques);
		builder.append("\", \n\t\"sex\" : \"");
		builder.append(sex);
		builder.append("\", \n\t\"photoImgId\" : \"");
		builder.append(photoImgId);
		builder.append("\", \n\t\"mobilePhone\" : \"");
		builder.append(mobilePhone);
		builder.append("\", \n\t\"areaId\" : \"");
		builder.append(areaId);
		builder.append("\", \n\t\"age\" : \"");
		builder.append(age);
		builder.append("\", \n\t\"star\" : \"");
		builder.append(star);
		builder.append("\", \n\t\"phcode\" : \"");
		builder.append(phcode);
		builder.append("\", \n\t\"areaName\" : \"");
		builder.append(areaName);
		builder.append("\"\n}");
		return builder.toString();
	}
	
	
}
